Retry `op item get` on failure

diff --git a/script/op-check-garbage-passwords b/script/op-check-garbage-passwords
--- a/script/op-check-garbage-passwords
+++ b/script/op-check-garbage-passwords
@@ -31,8 +31,12 @@ function op_check_garbage_passwords() {
     # shellcheck disable=SC2064
     trap "cleanup '$garbage_vault' '$op_user'" EXIT
 
-    for id in $(op item list --categories Login --format=json | jq -r '.[] | select(.id != null) | .id'); do
-        item=$(op item get "$id" --format=json)
+    for id in $(op item list --categories Login --format=json --vault CB | jq -r '.[] | select(.id != null) | .id'); do
+        while ! item=$(op item get "$id" --format=json); do
+            echo "Error loading '$id'; trying again in 5s"
+            sleep 5s
+        done
+
         if [[ $item != null ]]; then
             fields=$(jq -r '.fields' <<<"$item")
             if [[ $fields != null ]]; then
