Improve op-check-garbage-passwords script (#327)
* Default to empty `.tags`

* Ensure 1Password CLI is logged into account before adding "Garbage" vault

* Retry `op item get` on failure

* Remove duplicate removal of garbage vault

diff --git a/script/op-check-garbage-passwords b/script/op-check-garbage-passwords
--- a/script/op-check-garbage-passwords
+++ b/script/op-check-garbage-passwords
@@ -14,7 +14,7 @@ function cleanup() {
 
 function op_check_garbage_passwords() {
     local garbage_vault="${1:-ai37vtvl2day77mrnfu6kclega}"
-    local op_user="${2:-$(op whoami --format=json | jq -r '.email')}"
+    local op_user="${2:-$(op signin && op whoami --format=json | jq -r '.email')}"
     local id
     local item
     local fields
@@ -26,7 +26,11 @@ function op_check_garbage_passwords() {
     trap "cleanup '$garbage_vault' '$op_user'" EXIT
 
     for id in $(op item list --categories Login --format=json | jq -r '.[] | select(.id != null) | .id'); do
-        item=$(op item get "$id" --format=json)
+        while ! item=$(op item get "$id" --format=json); do
+            echo "Error loading '$id'; trying again in 5s"
+            sleep 5s
+        done
+
         if [[ $item != null ]]; then
             fields=$(jq -r '.fields' <<<"$item")
             if [[ $fields != null ]]; then
@@ -39,13 +43,11 @@ function op_check_garbage_passwords() {
                 else
                     idForPw[$pw]=$id
                 fi
-            elif jq -e '.tags | contains(["NoPasswordOk"]) | not' <<<"$item" >/dev/null ; then
+            elif jq -e '.tags // [] | contains(["NoPasswordOk"]) | not' <<<"$item" >/dev/null ; then
                 echo "Empty password for id $id"
             fi
         fi
     done
-
-    op vault user revoke --vault "$garbage_vault" --user "$op_user" >/dev/null
 }
 
 op_check_garbage_passwords "$@"
